- name: aws_ec2
  # hosts: host
  become: yes
  # become_user: root
  # become_method: sudo
  tasks:
    - name: pull the latest Docker img
      docker_image:
        name: khinesss/nodejs-app
        tag: latest
        pull: yes

    - name: Stop exitsting container
      docker_container:
        name: nodejs-app
        state: stopped
        ignore_errors: yes

    - name: Remove the exitsting container
      docker_container:
        name: nodejs-app
        state: absent
        ignore_errors: yes

    - name: Run the new container
      docker_container:
        name: nodejs-app
        image: khinesss/nodejs-app:latest
        state: started
        ports:
          - "80:80"